version: '3.8'

services:
  youtube-transcriber:
    build: .
    container_name: youtube-transcriber
    environment:
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION:-westeurope}
      - TRANSCRIPTION_LANGUAGE=${TRANSCRIPTION_LANGUAGE:-en-US}
      - OUTPUT_FORMATS=${OUTPUT_FORMATS:-txt,json,srt}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    command: transcribe